#!/usr/bin/env python3
"""Build the interactive audit dashboard as a single self-contained HTML file.

Usage:
    python dashboard/build_dashboard.py

Reads dashboard_data.json (generated by the pipeline) and embeds it into
dashboard/template.html -> dashboard/index.html (self-contained, no server needed).
"""
import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
ROOT = SCRIPT_DIR.parent
DATA_PATH = ROOT / "dashboard_data.json"
TEMPLATE_PATH = SCRIPT_DIR / "template.html"
OUTPUT_PATH = SCRIPT_DIR / "index.html"


def build():
    data = DATA_PATH.read_text(encoding="utf-8")
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    html = template.replace("/* __DASHBOARD_DATA__ */", f"const DATA = {data};")
    OUTPUT_PATH.write_text(html, encoding="utf-8")
    print(f"Dashboard built: {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    build()
